apiVersion: v1
kind: Service

metadata:
  name: java-devsecops-service
  namespace: devsecops-ai

spec:
  selector:
    app: java-devsecops-ai

  ports:
  - port: 80
    targetPort: 8080

  type: NodePort