pipeline {

    agent any

    environment {
        IMAGE_NAME = "auth-service:v1"
    }

    stages {

        stage('Clone Repository') {
            steps {
                checkout scm
            }
        }

        stage('Build Maven') {
            steps {
                dir('services/auth-service') {
                    sh 'chmod +x mvnw'
                    sh './mvnw clean package'
                }
            }
        }

        stage('Build Docker Image') {
            steps {
                dir('services/auth-service') {
                    sh 'docker build -t $IMAGE_NAME .'
                }
            }
        }

        stage('Deploy to Kubernetes') {
            steps {
                dir('services/auth-service') {
                    sh 'kubectl apply -f k8s/'
                }
            }
        }

        stage('Verify Deployment') {
            steps {
                sh 'kubectl get pods -n devsecops-ai'
            }
        }
    }
}